[G2M] Table with bar prototype
EQWorks/widget-studio pull request #220
Opened 2023-02-03 21:40 UTC by kc-leung

fixes #216 

Need: https://github.com/EQWorks/lumen-table/pull/38 

- Added table widget with barColumn display option
- Added multiple unique control options for table widget (  hidePagination, headerTitle, compactTable, centerHeader, barColumns, borderType and headerColor )

![Screenshot 2023-02-03 at 4 33 28 PM](https://user-images.githubusercontent.com/46459367/216715056-9a9e4409-1856-486a-8e7e-48f6668ab6b9.png)

2023-02-08 20:53 UTC, Hamaad102 approved these changes

2023-02-08 20:55 UTC, Hamaad102 commented
Before merging this @kc-leung can you also bump lumen-labs

2023-02-08 21:11 UTC, geoerika commented
> Before merging this @kc-leung can you also bump lumen-labs

@kc-leung leave it, I already did it in my following PR.

2023-02-08 21:56 UTC, geoerika requested changes
@kc-leung a good start, but I would like the Display Option to be better styled to have it similar to the other widget controls.

2023-02-08 21:56 UTC, geoerika commented on src/constants/table-widget.js
> +export const tableUniqueOptions = {
Look in `constants/types` to refactor this.

2023-02-08 21:56 UTC, geoerika commented on src/controls/editor-mode/components/color-scheme-controls.js
> +  const getColorType = useMemo(() => {
@kc-leung I don't think I understand why you needed to restrict the color type picker for Table. No matter what you choose (HEX, RGB, HSL) the base color returned is always in HEX format.

2023-02-08 21:56 UTC, geoerika commented on src/controls/editor-mode/right-sidebar.js
> +            {![types.Map, types.TABLE].includes(type) &&
Typo error: it is `types.MAP`

2023-02-08 21:56 UTC, geoerika commented on src/constants/type-info.js
> +        name: 'Hide Pagination',
Change name to simple: `Pagination`

2023-02-08 21:56 UTC, geoerika commented on src/constants/type-info.js
> +        name: 'Center Header',
Change Name to`Centered Header`. We tend not to use verbs in these names. I just change it to keep consistency.

2023-02-08 21:56 UTC, geoerika commented on src/controls/editor-mode/components/unique-option-controls.js
> +      <div className={classes.uniqueOptionsBooleanContainer}>
This breaks with the styling for the other widgets. Please check the styling for Display options (specifically the space between the rows of different elements) for the bar widget stories and add styling to match the section there.

The lower part grid for the outlined area should use all the space in the row, each radio should have the same space.
<img width="355" alt="Screen Shot 2023-02-08 at 4 53 23 PM" src="https://user-images.githubusercontent.com/41120953/217660015-119074f0-0ba7-4298-97c3-e9fffb28b053.png">

2023-02-10 17:22 UTC, geoerika approved these changes
Looks good!

2023-02-10 17:40 UTC, vlatawiec approved these changes

2023-02-10 18:25 UTC, merged